name: Update Download Badge

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get total downloads
        id: get_downloads
        run: |
          curl -s "https://api.github.com/repos/OWNER/REPO/releases" > releases.json
          TOTAL=$(jq '[.[] | .assets[]?.download_count] | add' releases.json)
          echo "total_downloads=$TOTAL" >> $GITHUB_ENV

      - name: Create badge JSON
        run: |
          mkdir -p .badges
          cat <<EOF > .badges/downloads.json
          {
            "schemaVersion": 1,
            "label": "downloads",
            "message": "${{ env.total_downloads }}",
            "color": "blue"
          }
          EOF

      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .badges/downloads.json
          git commit -m "Update download count badge" || echo "No changes"
          git push
